server:
   port: 3333

spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:1001/
        predicates:
         - Path=/userApi/**
         
      - uri: http://localhost:1002/
        predicates:
         - Path=/demo1002/**
         
      - uri: http://localhost:1003/
        predicates:
         - Path=/demo1003/**
         
      - uri: http://localhost:1004/
        predicates:
         - Path=/demo1004/**